### ISSUE TITLE
Sampling Speed and Buffering?

### ISSUE THREAD

**Issue by bhclowers** [robert-hh/ADS7818#1]
Have you explored the sample throughput of this unit to a board running micropython (e.g. pyboard-D or wipy)?  I was curious to know whether this unit could be used to provide higher resolution ADC into an array?  That data sheet suggest a maximum of 500 kSps but even half that would be fantastic.

**Comment by robert-hh** [comment]
I did not test that. There a  few limits to speed. First of all the transfer times. This driver uses 16 SPI clock cycles. At 4 MHz that alone would limit it to 250 ksamples/s. Then, the data has to be processed. I would be surprised if more than 50 kSamples/s could be achieved.  For Pyboard D and Pyboard 1.1, you could also used the timed adc reading pyb.read_timed().  But the internal ADC is also not faster than about 60 kSamples/s. So: no joy using Micropython.

**Comment by bhclowers** [comment]
The read_timed seems to be providing some decent results so I will keep pulling on that thread.  Also, thanks for all your helpful responses on the forum.
